# Generated by Django 5.1.7 on 2025-03-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('bookingDetails', models.TextField()),
                ('eventPage', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('rejected', models.BooleanField(default=False)),
                ('googleCalendarEntry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.googlecalendarentry')),
            ],
        ),
    ]
