# Generated by Django 5.2.1 on 2025-05-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlecalendarentry',
            old_name='recurringEventId',
            new_name='recurring_event_id',
        ),
    ]
