# Generated by Django 5.2.1 on 2025-07-09 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rejected_event_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='googleCalendarEntry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.googlecalendarentry'),
        ),
    ]
