# Generated by Django 5.2.1 on 2025-06-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_recurringeventid_googlecalendarentry_recurring_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlecalendarentry',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='googlecalendarentry',
            old_name='google_event_id',
            new_name='googleEventId',
        ),
        migrations.RenameField(
            model_name='googlecalendarentry',
            old_name='last_updated',
            new_name='lastUpdated',
        ),
        migrations.RenameField(
            model_name='googlecalendarentry',
            old_name='recurring_event_id',
            new_name='recurringEventId',
        ),
        migrations.RenameField(
            model_name='googlecalendarentry',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
