# Generated by Django 5.2.1 on 2025-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_googlecalendarentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarentry',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='googlecalendarentry',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
