# Generated by Django 5.2.1 on 2025-07-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_googlecalendarentry_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bookingLink',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventLink',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='googleCalendarEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.googlecalendarentry'),
        ),
        migrations.AlterField(
            model_name='googlecalendarentry',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googlecalendarentry',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarentry',
            name='recurringEventId',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googlecalendarentry',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
